-- Layer 1: User Daily Activity View
-- Grain: 1 Row per Active User × Day × Action
-- Purpose: Inverted join to prevent 35.79% metric inflation, filters failed chats, sanitizes emails.
-- Authority Spine: Sourced directly from USERS_DAILY_AT.
-- Version Tracking: Integrates the 100% complete PRODUCT_VERSION_ADOPTION table.
-- Lineage Optimization: Completely purged all dependencies on legacy Postgres 'POSTGRES_LICENSEBILLING_TBL_' tables!

CREATE OR REPLACE VIEW DISCOVERY_PRODUCT_MANAGEMENT.METRIC_STORE.SEM_COPILOT_USER_ACTIVITY_ENRICHED AS
WITH ayx_user_day AS (
    SELECT
        DATE AS user_snapshot_date,
        DATE_TRUNC('MONTH', DATE)::DATE AS user_snapshot_month,
        USER_ID_RAW,
        LOWER(TRIM(SPLIT_PART(REPLACE(USER_EMAIL, ' ', ''), ';', 1))) AS email_lc,
        USER_EMAIL,
        LICENSE_TYPE,
        STATUS,
        COPILOT_ENABLED,
        ACCOUNT_EDITION,
        PRICING_AND_PACKAGING,
        PIPELINE_REGION,
        BILLING_ACCOUNT_ID,
        BILLING_ACCOUNT_ID_RAW,
        SFDC_ACCOUNT_ID,
        ACCOUNT_CID,
        BILLING_ACCOUNT_NAME
    FROM DISCOVERY_PRODUCT_MANAGEMENT.METRIC_STORE.USERS_DAILY_AT
    WHERE DATE >= '2025-12-03'::DATE AND USER_ID_RAW IS NOT NULL AND DATE IS NOT NULL
    QUALIFY ROW_NUMBER() OVER (PARTITION BY USER_ID_RAW, DATE ORDER BY STATUS DESC, LICENSE_TYPE DESC) = 1
),
cm_raw AS (
    SELECT
        cm.*,
        LOWER(TRIM(SPLIT_PART(REPLACE(cm.USER_EMAIL, ' ', ''), ';', 1))) AS cm_email_lc,
        TRY_TO_NUMBER(cm.EXTERNAL_ID) AS ext_id_num,
        CAST(cm.CONV_CREATED_DATE AS DATE) AS activity_day
    FROM DISCOVERY_ENGINEERING.COPILOT.COPILOT_USAGE_ALL_REGIONS_VW cm
    WHERE CONV_CREATED_DATE >= '2025-12-03'
),
cm AS (
    SELECT cm.*
    FROM cm_raw cm
    LEFT JOIN DISCOVERY_ENGINEERING.COPILOT.COPILOT_CHAT ch
        ON cm.CHAT_ID = ch.ID
    WHERE ch.ID IS NULL OR COALESCE(LOWER(ch.STATUS), 'success') <> 'failed'
),
pva AS (
    SELECT DISTINCT
        TRY_TO_NUMBER(SPLIT_PART(BASE64_DECODE_STRING(USER_ID), '_', 1)) AS decoded_user_id,
        YEAR_MONTH AS pva_month,
        "Max_User_VERSION" AS observed_version
    FROM DISCOVERY_PRODUCT_MANAGEMENT.TEL_STRAT.PRODUCT_VERSION_ADOPTION
    WHERE YEAR_MONTH >= '2025-12-03'
    QUALIFY ROW_NUMBER() OVER (PARTITION BY decoded_user_id, YEAR_MONTH ORDER BY LAST_UPDATED DESC) = 1
)
SELECT
    -- 1. Date columns
    cm.activity_day AS ACTIVITY_DATE, -- The specific calendar day when the active Copilot telemetry log occurred.
    u.user_snapshot_month AS MONTH_START_DATE, -- First day of the calendar month corresponding to the activity date (e.g. 2026-06-01) used for cohort groupings.
    
    -- 2. User Info
    COALESCE(cm.cm_email_lc, u.email_lc) AS USER_EMAIL, -- The standardized, lowercase email address of the active user.
    COALESCE(cm.ext_id_num, u.USER_ID_RAW) AS USER_ID_RAW, -- The primary unique numeric identifier of the user, used for database-level joins.
    
    -- 3. Associated Account Info
    u.BILLING_ACCOUNT_ID_RAW AS BILLING_ACCOUNT_ID_RAW, -- The raw, decoded billing account ID representing AlteryxOne on-premise accounts.
    u.BILLING_ACCOUNT_ID AS BILLING_ACCOUNT_ID, -- The base64-encoded AlteryxOne billing account ID.
    u.ACCOUNT_EDITION AS ACCOUNT_EDITION, -- The contract edition assigned to the user's account (e.g., Professional, Enterprise).
    u.SFDC_ACCOUNT_ID AS SFDC_ACCOUNT_ID, -- The 15-character master Salesforce Account ID.
    u.ACCOUNT_CID AS ACCOUNT_CID, -- The Customer ID (CID) hash matching the Salesforce Account.
    u.BILLING_ACCOUNT_NAME AS BILLING_ACCOUNT_NAME, -- The master Billing Customer Name associated with the user's profile.
    u.LICENSE_TYPE AS LICENSE_TYPE, -- The normalized license type (e.g., Purchase, Trial, Evaluation) with synonyms resolved.
    u.PRICING_AND_PACKAGING AS PRICING_AND_PACKAGING, -- The contract pricing model and packaging tier assigned to the profile.
    COALESCE(NULLIF(TRIM(u.ACCOUNT_CID), ''), NULLIF(TRIM(u.SFDC_ACCOUNT_ID), ''), 'Shadow Account') AS FINAL_ACCOUNT_CID, -- Unified account match key waterfall used to prevent fanning during Salesforce dimensions joins.
    
    -- 4. Telemetry and Others
    cm.CONVERSATION_ID AS CONVERSATION_ID, -- Unique session ID hash mapping to the specific active conversation session.
    cm.CHAT_ID AS CHAT_ID, -- Unique successful prompt ID (failed or timed-out prompts are strictly pruned out).
    cm.METRIC_ID AS METRIC_ID, -- Unique metric ID generated by the interaction.
    cm.WORKFLOW_ID AS WORKFLOW_ID, -- Unique workflow generation ID indicating Alteryx Designer workflow dropping actions.
    COALESCE(cm.USER_WITH_CONVERSATION, FALSE) AS USER_WITH_CONVERSATION, -- Boolean flag indicating whether the user initiated a valid conversation session.
    COALESCE(cm.USER_WITH_CHAT, FALSE) AS USER_WITH_CHAT, -- Boolean flag indicating whether the user successfully executed a prompt.
    COALESCE(cm.USER_WITH_METRIC, FALSE) AS USER_WITH_METRIC, -- Boolean flag indicating whether the interaction generated metric logs.
    COALESCE(cm.USER_WITH_WORKFLOW, FALSE) AS USER_WITH_WORKFLOW, -- Boolean flag indicating whether the user successfully generated/touched a workflow.
    COALESCE(uv.observed_version, '2025.2') AS MAX_USER_VERSION_OBSERVED, -- The highest observed software version of the active user mapped from PRODUCT_VERSION_ADOPTION.
    u.PIPELINE_REGION AS PIPELINE_REGION, -- The endpoint pipeline execution deployment region (e.g., US, EU, AU).
    u.STATUS AS STATUS, -- The activation state of the user's profile inside the daily users snapshot database.
    u.COPILOT_ENABLED AS COPILOT_ENABLED -- Boolean flag indicating whether the Copilot feature is actively enabled on the user's account.
FROM cm
LEFT JOIN ayx_user_day u
    ON cm.ext_id_num = u.USER_ID_RAW
   AND cm.activity_day = u.user_snapshot_date
LEFT JOIN pva uv
    ON u.USER_ID_RAW = uv.decoded_user_id
   AND u.user_snapshot_month = DATE_TRUNC('MONTH', uv.pva_month)::DATE
WHERE SPLIT_PART(COALESCE(cm.cm_email_lc, u.email_lc), '@', 2) NOT LIKE '%alteryx.com%'
  AND SPLIT_PART(COALESCE(cm.cm_email_lc, u.email_lc), '@', 2) NOT LIKE '%aleeas.com%';