-- Layer 2: User Daily Aggregated View
-- Grain: 1 Row per User × Day
-- Purpose: Deduplicates active metrics using COUNT(DISTINCT) over the granular L1 View.

CREATE OR REPLACE VIEW DISCOVERY_PRODUCT_MANAGEMENT.METRIC_STORE.SEM_COPILOT_USER_DAILY AS
WITH daily AS (
    SELECT
        ACTIVITY_DATE,
        MONTH_START_DATE,
        USER_EMAIL,
        MAX(USER_ID_RAW) AS USER_ID_RAW,
        MAX(FINAL_ACCOUNT_CID) AS FINAL_ACCOUNT_CID,
        MAX(BILLING_ACCOUNT_ID_RAW) AS BILLING_ACCOUNT_ID_RAW,
        MAX(BILLING_ACCOUNT_ID) AS BILLING_ACCOUNT_ID,
        MAX(ACCOUNT_EDITION) AS ACCOUNT_EDITION,
        MAX(SFDC_ACCOUNT_ID) AS SFDC_ACCOUNT_ID,
        MAX(ACCOUNT_CID) AS ACCOUNT_CID,
        MAX(BILLING_ACCOUNT_NAME) AS BILLING_ACCOUNT_NAME,
        MAX(LICENSE_TYPE) AS LICENSE_TYPE,
        MAX(PRICING_AND_PACKAGING) AS PRICING_AND_PACKAGING,
        MAX(MAX_USER_VERSION_OBSERVED) AS MAX_USER_VERSION_OBSERVED,
        MAX(PIPELINE_REGION) AS PIPELINE_REGION,
        MAX(STATUS) AS STATUS,
        MAX(COPILOT_ENABLED) AS COPILOT_ENABLED,
        
        -- Deduplicated metric aggregations
        COUNT(DISTINCT CONVERSATION_ID) AS CONVERSATIONS,
        COUNT(DISTINCT CASE WHEN CHAT_ID IS NOT NULL THEN CONVERSATION_ID END) AS CHAT_CONVERSATIONS,
        COUNT(DISTINCT CHAT_ID) AS CHATS,
        COUNT(DISTINCT METRIC_ID) AS METRICS,
        COUNT(DISTINCT WORKFLOW_ID) AS WORKFLOWS_TOUCHED,
        
        -- Boolean indicators
        MAX(IFF(USER_WITH_CONVERSATION, 1, 0)) AS HAD_CONVERSATION,
        MAX(IFF(USER_WITH_CHAT, 1, 0)) AS HAD_CHAT,
        MAX(IFF(USER_WITH_METRIC, 1, 0)) AS HAD_METRIC,
        MAX(IFF(USER_WITH_WORKFLOW, 1, 0)) AS HAD_WORKFLOW
    FROM DISCOVERY_PRODUCT_MANAGEMENT.METRIC_STORE.SEM_COPILOT_USER_ACTIVITY_ENRICHED
    GROUP BY 1, 2, 3
)
SELECT
    daily.*,
    ROUND(CHATS / NULLIF(CONVERSATIONS, 0), 2) AS CHATS_PER_CONVERSATION
FROM daily;