-- Layer 3: Monthly Account Aggregated View
-- Grain: 1 Row per Account × Month
-- Purpose: Uses CID-First COALESCE waterfall to match 96%+ of Salesforce CRM data. Direct from L1.

CREATE OR REPLACE VIEW DISCOVERY_PRODUCT_MANAGEMENT.METRIC_STORE.SEM_COPILOT_ACCOUNT_MONTHLY AS
WITH user_month AS (
    SELECT
        MONTH_START_DATE,
        FINAL_ACCOUNT_CID,
        USER_EMAIL,
        COUNT(DISTINCT CONVERSATION_ID) AS CONVERSATIONS,
        COUNT(DISTINCT CASE WHEN CHAT_ID IS NOT NULL THEN CONVERSATION_ID END) AS CHAT_CONVERSATIONS,
        COUNT(DISTINCT CHAT_ID) AS CHATS,
        COUNT(DISTINCT METRIC_ID) AS METRICS,
        COUNT(DISTINCT WORKFLOW_ID) AS WORKFLOWS_TOUCHED,
        COUNT(DISTINCT IFF(CHAT_ID IS NOT NULL, ACTIVITY_DATE, NULL)) AS ACTIVE_DAYS
    FROM DISCOVERY_PRODUCT_MANAGEMENT.METRIC_STORE.SEM_COPILOT_USER_ACTIVITY_ENRICHED
    WHERE FINAL_ACCOUNT_CID <> 'Shadow Account'
    GROUP BY 1, 2, 3
),
acct_dim AS (
    SELECT
        DATE_TRUNC('MONTH', YEAR_MONTH)::DATE AS reporting_month,
        COALESCE(NULLIF(TRIM(ACCOUNT_CID), ''), NULLIF(TRIM(SFDC_ACCOUNT_ID), '')) AS account_key,
        ACCOUNT_CID, SFDC_ACCOUNT_ID,
        BILLING_ACCOUNT_NAME, NAMED_COMPANY,
        ACCOUNT_SALES_REGION, ACCOUNT_SALES_SEGMENT, CLOUD_ACV, INDUSTRY, COUNTRY
    FROM DISCOVERY_PRODUCT_MANAGEMENT.METRIC_STORE.AYX_MONTHLY_ACCOUNT_AT
    WHERE COALESCE(ACCOUNT_CID, SFDC_ACCOUNT_ID) IS NOT NULL AND YEAR_MONTH >= '2025-12-03'
    QUALIFY ROW_NUMBER() OVER (
        PARTITION BY COALESCE(NULLIF(TRIM(ACCOUNT_CID), ''), NULLIF(TRIM(SFDC_ACCOUNT_ID), '')), DATE_TRUNC('MONTH', YEAR_MONTH)
        ORDER BY CLOUD_ACV DESC NULLS LAST) = 1
),
agg AS (
    SELECT
        MONTH_START_DATE AS REPORTING_MONTH,
        FINAL_ACCOUNT_CID AS CUSTOMER_ID,
        COUNT(DISTINCT USER_EMAIL) AS TOTAL_USERS,
        COUNT(DISTINCT IFF(CHAT_CONVERSATIONS > 0, USER_EMAIL, NULL)) AS TOTAL_ACTIVE_USERS,
        SUM(CONVERSATIONS) AS CONVERSATIONS,
        SUM(CHATS) AS CHATS,
        SUM(METRICS) AS METRICS,
        SUM(WORKFLOWS_TOUCHED) AS WORKFLOWS_TOUCHED
    FROM user_month
    GROUP BY 1, 2
)
SELECT
    a.REPORTING_MONTH,
    a.CUSTOMER_ID,
    d.BILLING_ACCOUNT_NAME AS CUSTOMER_NAME,
    d.NAMED_COMPANY AS COMPANY_GROUP,
    a.TOTAL_USERS,
    a.TOTAL_ACTIVE_USERS,
    a.CONVERSATIONS,
    a.CHATS,
    a.METRICS,
    a.WORKFLOWS_TOUCHED,
    d.ACCOUNT_SALES_REGION AS SALES_REGION,
    d.ACCOUNT_SALES_SEGMENT AS MARKET_SEGMENT,
    COALESCE(d.CLOUD_ACV, 0.0) AS CLOUD_ACV
FROM agg a
LEFT JOIN acct_dim d
    ON a.CUSTOMER_ID = d.account_key
   AND a.REPORTING_MONTH = d.reporting_month;