-- Layer 3: Monthly Account Aggregated View
-- Grain: 1 Row per Account × Month
-- Purpose: Uses CID-First COALESCE waterfall to match 96%+ of Salesforce CRM data. Direct from L1.
-- Column Comments: Strictly compiled inside Snowflake using native metadata comments.

CREATE OR REPLACE VIEW DISCOVERY_PRODUCT_MANAGEMENT.METRIC_STORE.SEM_COPILOT_ACCOUNT_MONTHLY(
    REPORTING_MONTH COMMENT 'First day of the calendar month representing the reporting interval.',
    CUSTOMER_ID COMMENT 'The coalesced unique customer ID waterfall used to link telemetry to Salesforce accounts.',
    CUSTOMER_NAME COMMENT 'The master Billing Customer Name associated with the user profile.',
    COMPANY_GROUP COMMENT 'The standardized parent company name mapped from Salesforce.',
    TOTAL_USERS COMMENT 'Total registered users on that account during the month.',
    TOTAL_ACTIVE_USERS COMMENT 'Monthly Active Users (MAU) of the Copilot feature.',
    CONVERSATIONS COMMENT 'The total count of distinct conversation threads generated by this account.',
    CHATS COMMENT 'The total number of successful prompts executed by this account during the month.',
    METRICS COMMENT 'The total count of distinct metric interactions compiled during the month.',
    WORKFLOWS_TOUCHED COMMENT 'The total count of distinct Alteryx workflows created or modified using Copilot.',
    SALES_REGION COMMENT 'The global sales region mapped from Salesforce.',
    MARKET_SEGMENT COMMENT 'The market segment of the customer mapped from Salesforce.',
    CLOUD_ACV COMMENT 'The active annual contract value (ACV) of the customer mapped from Salesforce.'
) AS
WITH user_month AS (
    SELECT
        MONTH_START_DATE,
        FINAL_ACCOUNT_CID,
        USER_EMAIL,
        COUNT(DISTINCT CONVERSATION_ID) AS CONVERSATIONS,
        COUNT(DISTINCT CASE WHEN CHAT_ID IS NOT NULL THEN CONVERSATION_ID END) AS CHAT_CONVERSATIONS,
        COUNT(DISTINCT CHAT_ID) AS CHATS,
        COUNT(DISTINCT METRIC_ID) AS METRICS,
        COUNT(DISTINCT WORKFLOW_ID) AS WORKFLOWS_TOUCHED,
        COUNT(DISTINCT IFF(CHAT_ID IS NOT NULL, ACTIVITY_DATE, NULL)) AS ACTIVE_DAYS
    FROM DISCOVERY_PRODUCT_MANAGEMENT.METRIC_STORE.SEM_COPILOT_USER_ACTIVITY_ENRICHED
    WHERE FINAL_ACCOUNT_CID <> 'Shadow Account'
    GROUP BY 1, 2, 3
),
acct_dim AS (
    SELECT
        DATE_TRUNC('MONTH', YEAR_MONTH)::DATE AS reporting_month,
        COALESCE(NULLIF(TRIM(ACCOUNT_CID), ''), NULLIF(TRIM(SFDC_ACCOUNT_ID), '')) AS account_key,
        ACCOUNT_CID, SFDC_ACCOUNT_ID,
        BILLING_ACCOUNT_NAME, NAMED_COMPANY,
        ACCOUNT_SALES_REGION, ACCOUNT_SALES_SEGMENT, CLOUD_ACV, INDUSTRY, COUNTRY,
        BILLING_ACCOUNT_ID_RAW, LICENSE_TYPE, PRICING_AND_PACKAGING
    FROM DISCOVERY_PRODUCT_MANAGEMENT.METRIC_STORE.AYX_MONTHLY_ACCOUNT_AT
    WHERE COALESCE(ACCOUNT_CID, SFDC_ACCOUNT_ID) IS NOT NULL AND YEAR_MONTH >= '2025-12-03'
    QUALIFY ROW_NUMBER() OVER (
        PARTITION BY COALESCE(NULLIF(TRIM(ACCOUNT_CID), ''), NULLIF(TRIM(SFDC_ACCOUNT_ID), '')) , DATE_TRUNC('MONTH', YEAR_MONTH)
        ORDER BY CLOUD_ACV DESC NULLS LAST) = 1
),
agg AS (
    SELECT
        MONTH_START_DATE AS REPORTING_MONTH,
        FINAL_ACCOUNT_CID AS CUSTOMER_ID,
        COUNT(DISTINCT USER_EMAIL) AS TOTAL_USERS,
        COUNT(DISTINCT IFF(CHAT_CONVERSATIONS > 0, USER_EMAIL, NULL)) AS TOTAL_ACTIVE_USERS,
        SUM(CONVERSATIONS) AS CONVERSATIONS,
        SUM(CHATS) AS CHATS,
        SUM(METRICS) AS METRICS,
        SUM(WORKFLOWS_TOUCHED) AS WORKFLOWS_TOUCHED
    FROM user_month
    GROUP BY 1, 2
)
SELECT
    a.REPORTING_MONTH,
    a.CUSTOMER_ID,
    d.BILLING_ACCOUNT_NAME,
    d.NAMED_COMPANY,
    a.TOTAL_USERS,
    a.TOTAL_ACTIVE_USERS,
    a.CONVERSATIONS,
    a.CHATS,
    a.METRICS,
    a.WORKFLOWS_TOUCHED,
    d.ACCOUNT_SALES_REGION,
    d.ACCOUNT_SALES_SEGMENT,
    COALESCE(d.CLOUD_ACV, 0.0)
FROM agg a
LEFT JOIN acct_dim d
    ON a.CUSTOMER_ID = d.account_key
   AND a.REPORTING_MONTH = d.reporting_month;