-- Layer 3: Monthly Account Aggregated View
-- Grain: 1 Row per Account × Month
-- Purpose: Uses CID-First COALESCE waterfall to match 96%+ of Salesforce CRM data. Direct from L1.

CREATE OR REPLACE VIEW DISCOVERY_PRODUCT_MANAGEMENT.METRIC_STORE.SEM_COPILOT_ACCOUNT_MONTHLY AS
WITH user_month AS (
    SELECT
        MONTH_START_DATE,
        FINAL_ACCOUNT_CID,
        USER_EMAIL,
        COUNT(DISTINCT CONVERSATION_ID) AS CONVERSATIONS,
        COUNT(DISTINCT CASE WHEN CHAT_ID IS NOT NULL THEN CONVERSATION_ID END) AS CHAT_CONVERSATIONS,
        COUNT(DISTINCT CHAT_ID) AS CHATS,
        COUNT(DISTINCT METRIC_ID) AS METRICS,
        COUNT(DISTINCT WORKFLOW_ID) AS WORKFLOWS_TOUCHED,
        COUNT(DISTINCT IFF(CHAT_ID IS NOT NULL, ACTIVITY_DATE, NULL)) AS ACTIVE_DAYS
    FROM DISCOVERY_PRODUCT_MANAGEMENT.METRIC_STORE.SEM_COPILOT_USER_ACTIVITY_ENRICHED
    WHERE FINAL_ACCOUNT_CID <> 'Shadow Account'
    GROUP BY 1, 2, 3
),
acct_dim AS (
    SELECT
        DATE_TRUNC('MONTH', YEAR_MONTH)::DATE AS reporting_month,
        COALESCE(NULLIF(TRIM(ACCOUNT_CID), ''), NULLIF(TRIM(SFDC_ACCOUNT_ID), '')) AS account_key,
        ACCOUNT_CID, SFDC_ACCOUNT_ID,
        BILLING_ACCOUNT_NAME, NAMED_COMPANY,
        ACCOUNT_SALES_REGION, ACCOUNT_SALES_SEGMENT, CLOUD_ACV, INDUSTRY, COUNTRY,
        BILLING_ACCOUNT_ID_RAW, LICENSE_TYPE, PRICING_AND_PACKAGING
    FROM DISCOVERY_PRODUCT_MANAGEMENT.METRIC_STORE.AYX_MONTHLY_ACCOUNT_AT
    WHERE COALESCE(ACCOUNT_CID, SFDC_ACCOUNT_ID) IS NOT NULL AND YEAR_MONTH >= '2025-12-03'
    QUALIFY ROW_NUMBER() OVER (
        PARTITION BY COALESCE(NULLIF(TRIM(ACCOUNT_CID), ''), NULLIF(TRIM(SFDC_ACCOUNT_ID), '')) , DATE_TRUNC('MONTH', YEAR_MONTH)
        ORDER BY CLOUD_ACV DESC NULLS LAST) = 1
),
agg AS (
    SELECT
        MONTH_START_DATE AS REPORTING_MONTH, -- First day of the calendar month representing the reporting interval.
        FINAL_ACCOUNT_CID AS CUSTOMER_ID, -- The coalesced unique customer ID waterfall used to link telemetry to Salesforce accounts.
        COUNT(DISTINCT USER_EMAIL) AS TOTAL_USERS, -- Total registered users on that account during the month.
        COUNT(DISTINCT IFF(CHAT_CONVERSATIONS > 0, USER_EMAIL, NULL)) AS TOTAL_ACTIVE_USERS, -- Monthly Active Users (MAU) of the Copilot feature.
        SUM(CONVERSATIONS) AS CONVERSATIONS, -- The total count of distinct conversation threads generated by this account.
        SUM(CHATS) AS CHATS, -- The total number of successful prompts executed by this account during the month.
        SUM(METRICS) AS METRICS, -- The total count of distinct metric interactions compiled during the month.
        SUM(WORKFLOWS_TOUCHED) AS WORKFLOWS_TOUCHED -- The total count of distinct Alteryx workflows created or modified using Copilot.
    FROM user_month
    GROUP BY 1, 2
)
SELECT
    a.REPORTING_MONTH, -- First day of the calendar month representing the reporting interval.
    a.CUSTOMER_ID, -- The coalesced unique customer ID waterfall used to link telemetry to Salesforce accounts.
    d.BILLING_ACCOUNT_NAME AS CUSTOMER_NAME, -- The master Billing Customer Name associated with the user's profile.
    d.NAMED_COMPANY AS COMPANY_GROUP, -- The standardized parent company name mapped from Salesforce.
    a.TOTAL_USERS, -- Total registered users on that account during the month.
    a.TOTAL_ACTIVE_USERS, -- Monthly Active Users (MAU) of the Copilot feature.
    a.CONVERSATIONS, -- The total count of distinct conversation threads generated by this account.
    a.CHATS, -- The total number of successful prompts executed by this account during the month.
    a.METRICS, -- The total count of distinct metric interactions compiled during the month.
    a.WORKFLOWS_TOUCHED, -- The total count of distinct Alteryx workflows created or modified using Copilot.
    d.ACCOUNT_SALES_REGION AS SALES_REGION, -- The global sales region mapped from Salesforce.
    d.ACCOUNT_SALES_SEGMENT AS MARKET_SEGMENT, -- The market segment of the customer mapped from Salesforce.
    COALESCE(d.CLOUD_ACV, 0.0) AS CLOUD_ACV -- The active annual contract value (ACV) of the customer mapped from Salesforce.
FROM agg a
LEFT JOIN acct_dim d
    ON a.CUSTOMER_ID = d.account_key
   AND a.REPORTING_MONTH = d.reporting_month;