-- Long-Term Metric Tracking: Snowflake-hosted Historical Snapshots
-- Purpose: Solves the long-term historical reporting problem by writing daily and monthly snapshots to persistent physical tables.

-- 1. Create Daily Historical Snapshot Table (Run nightly via Alteryx Server or Snowflake Task)
CREATE TABLE IF NOT EXISTS DISCOVERY_PRODUCT_MANAGEMENT.METRIC_STORE.SNAP_COPILOT_DAILY_USERS_HISTORICAL (
    ACTIVITY_DATE DATE,
    PIPELINE_REGION VARCHAR(10),
    LICENSE_TYPE VARCHAR(50),
    DAU_COUNT NUMBER,
    TOTAL_CHATS NUMBER,
    TOTAL_CONVERSATIONS NUMBER,
    TOTAL_WORKFLOWS NUMBER,
    SNAPSHOT_TIMESTAMP TIMESTAMP_TZ DEFAULT SYSTIMESTAMP()
);

-- Incremental Daily load query (idempotent, replaces existing partition if re-run)
DELETE FROM DISCOVERY_PRODUCT_MANAGEMENT.METRIC_STORE.SNAP_COPILOT_DAILY_USERS_HISTORICAL 
WHERE ACTIVITY_DATE = CURRENT_DATE() - 1;

INSERT INTO DISCOVERY_PRODUCT_MANAGEMENT.METRIC_STORE.SNAP_COPILOT_DAILY_USERS_HISTORICAL (
    ACTIVITY_DATE, PIPELINE_REGION, LICENSE_TYPE, DAU_COUNT, TOTAL_CHATS, TOTAL_CONVERSATIONS, TOTAL_WORKFLOWS
)
SELECT
    ACTIVITY_DATE,
    COALESCE(PIPELINE_REGION, 'US') AS PIPELINE_REGION,
    COALESCE(LICENSE_TYPE, 'Purchase') AS LICENSE_TYPE,
    COUNT(DISTINCT USER_EMAIL) AS DAU_COUNT,
    SUM(CHATS) AS TOTAL_CHATS,
    SUM(CONVERSATIONS) AS TOTAL_CONVERSATIONS,
    SUM(WORKFLOWS_TOUCHED) AS TOTAL_WORKFLOWS
FROM DISCOVERY_PRODUCT_MANAGEMENT.METRIC_STORE.SEM_COPILOT_USER_DAILY
WHERE ACTIVITY_DATE = CURRENT_DATE() - 1
GROUP BY 1, 2, 3;


-- 2. Create Monthly Historical Snapshot Table (Run on 1st of every month)
CREATE TABLE IF NOT EXISTS DISCOVERY_PRODUCT_MANAGEMENT.METRIC_STORE.SNAP_COPILOT_MONTHLY_ACCOUNTS_HISTORICAL (
    REPORTING_MONTH DATE,
    SALES_REGION VARCHAR(50),
    MARKET_SEGMENT VARCHAR(50),
    MAU_COUNT NUMBER,
    TOTAL_ACCOUNTS NUMBER,
    TOTAL_ACV_VALUE NUMBER(38,2),
    SNAPSHOT_TIMESTAMP TIMESTAMP_TZ DEFAULT SYSTIMESTAMP()
);

-- Incremental Monthly load query (run on 1st of every month for the previous month)
DELETE FROM DISCOVERY_PRODUCT_MANAGEMENT.METRIC_STORE.SNAP_COPILOT_MONTHLY_ACCOUNTS_HISTORICAL 
WHERE REPORTING_MONTH = DATE_TRUNC('MONTH', CURRENT_DATE() - 5)::DATE;

INSERT INTO DISCOVERY_PRODUCT_MANAGEMENT.METRIC_STORE.SNAP_COPILOT_MONTHLY_ACCOUNTS_HISTORICAL (
    REPORTING_MONTH, SALES_REGION, MARKET_SEGMENT, MAU_COUNT, TOTAL_ACCOUNTS, TOTAL_ACV_VALUE
)
SELECT
    REPORTING_MONTH,
    COALESCE(SALES_REGION, 'North America') AS SALES_REGION,
    COALESCE(MARKET_SEGMENT, 'Enterprise') AS MARKET_SEGMENT,
    SUM(TOTAL_ACTIVE_USERS) AS MAU_COUNT,
    COUNT(DISTINCT CUSTOMER_ID) AS TOTAL_ACCOUNTS,
    SUM(CLOUD_ACV) AS TOTAL_ACV_VALUE
FROM DISCOVERY_PRODUCT_MANAGEMENT.METRIC_STORE.SEM_COPILOT_ACCOUNT_MONTHLY
WHERE REPORTING_MONTH = DATE_TRUNC('MONTH', CURRENT_DATE() - 5)::DATE
GROUP BY 1, 2, 3;